### ISSUE TITLE
Upload to Pypi

### ISSUE THREAD

**Issue by ejether** [DiljotSG/1password-python#1]
Would you be willing to upload this to the Pypi repository?
I'm willing to PR that in or fork the project and do that if you'd prefer.

**Comment by DiljotSG** [comment]
I would love to upload this to Pypi. If you want to fork this project and make a PR for the changes required I would be happy to pull those in here.

**Comment by ejether** [comment]
Do you have a CI provider you prefer? I don't see a build config file in the repo currently. We use CircleCi. It is free for OpenSource projects and I have a snippet I can drop in easily. 

If you have another CI provider you prefer, I can set it up for that one.

**Comment by DiljotSG** [comment]
Circle CI is fine :smiley:
